/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9da1e1c56549f41759badfb050e69006)
interface __BaseEnv_Env {
	SLATE: KVNamespace;
	GITHUB_OWNER: "kalb2";
	GITHUB_REPO: "nfl-missed-kick-bot";
	GITHUB_EVENT_TYPE: "nfl-poll";
	PRE_KICKOFF_MIN: "30";
	POST_KICKOFF_MIN: "285";
	DISPATCH_COOLDOWN_MIN: "5";
	SLATE_MAX_AGE_HOURS: "168";
	REFRESH_MIN_INTERVAL_HOURS: "6";
	LOOKAHEAD_DAYS: "16";
	ESPN_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36";
	GITHUB_TOKEN: string;
	SCHEDULER_ADMIN_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_EVENT_TYPE" | "PRE_KICKOFF_MIN" | "POST_KICKOFF_MIN" | "DISPATCH_COOLDOWN_MIN" | "SLATE_MAX_AGE_HOURS" | "REFRESH_MIN_INTERVAL_HOURS" | "LOOKAHEAD_DAYS" | "ESPN_USER_AGENT" | "GITHUB_TOKEN" | "SCHEDULER_ADMIN_SECRET">> {}
}
